platform :ios, '9.0'

target 'ios-whatnews-demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-whatnews-demo
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'SVProgressHUD'
end
